### ISSUE TITLE
Create approve/reject user modal

### ISSUE THREAD

**Issue by sahithimuthyala** [hack4impact-uiuc/south-side-weekly#184]
## Description

Create the approve/reject user modal for admin. This modal should open up when the user clicks on a row in the "Pending Users" table in the "Pending Users" tab in the admin directory.

## Todo

- [x] Modal design
- [x] Store the optional message (preferably only if the user is rejected, but either way works if that is easier)
- [x] Approve/reject users on backend (change onboarding status)
- [x] Keep track of users

## Useful links

- https://www.figma.com/file/MHRVK2dRznJ3mSogT57dM5/%5BFa21%5D-SSW-Bryan's-Designs?node-id=621%3A38842

**Comment by sahithimuthyala** [comment]
@zorazrr @chenfeiyu132 There is some overlap between your issues (approve/reject users on backend (change onboarding status) and keep track of users). You should work together on that backend functionality and then work together on your frontend portions separately (Zora will work on the approve/reject user modal UI, while Andy will work on the approve/reject table UI). One of you will have the backend logic and once the frontend work is done, we will merge that in and integrate it in with the other.
